#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get -y update
sudo apt install -y haproxy

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend yahyabn-tech-frontend
    bind *:80
    default_backend yahyabn-tech-backend

backend yahyabn-tech-backend
    balance roundrobin
    server 520514-web-01 54.166.81.116:80 check
    server 520514-web-02 3.90.82.143:80 check
"

sudo echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

