#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

count=1

while [ $count -le 20 ]
do
    echo "$count"

    if [ "$count" -eq 4 ]
    then
        echo "bad luck from China"
    elif [ "$count" -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ "$count" -eq 17 ]
    then
        echo "bad luck from Italy"
    fi
    ((count++))
done
